### ISSUE TITLE
Allow for normal programming too!

### ISSUE THREAD

**Issue by fotherja** [jbateman3/ArduinoIR#1]
Allow for normal sketch upload using wires if that's available, otherwise resort to IR upload.

**Comment by jbateman3** [comment]
Added! The micro can now be programmed with serial over digital pins 1 and 3. 

TODO: switch UART and IR programming pins around so that the IR receiver can be on any pin and standard arduino boards can be programmed by simply plugging in the USB connector.

**Comment by jbateman3** [comment]
TODO done!
The micro can now be programmed with serial on pins 0 and 1 at full speed. IR programming is now on pin 11 to be compatible with the GMC.
